### PR TITLE
Docker build of locust

### PR DESCRIPTION
**Pull request by nkashy1**
This is part of the work of setting up the Locust GitHub Action, which we will create as a Docker action (https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action).

Edit: I expanded this PR in scope a bit, to also support the use case for Locust inside GitHub Actions. I feel this is justified, as we started the dockerization work for GitHub Actions in the first place.

### CODE REVIEW

**Review by kompotkot — APPROVED** [review]

**Comment by kompotkot** [comment]
Hm somethings goes wrong with command
` docker run -v ~/Downloads/nkashy1-locust bugout/locust -r ~/Downloads/nkashy1-locust master HEAD --format yaml`
```
Traceback (most recent call last):
  File "/usr/local/bin/locust", line 33, in <module>
    sys.exit(load_entry_point('bugout-locust==0.1.0', 'console_scripts', 'locust')())
  File "/usr/local/lib/python3.8/site-packages/bugout_locust-0.1.0-py3.8.egg/locust/cli.py", line 69, in main
  File "/usr/local/lib/python3.8/site-packages/bugout_locust-0.1.0-py3.8.egg/locust/git.py", line 47, in get_repository
locust.git.GitRepositoryNotFound: No git repository found at path:/home/user/Downloads/nkashy1-locust
```

**Comment by nkashy1** [comment]
> Hm somethings goes wrong with command
> ` docker run -v ~/Downloads/nkashy1-locust bugout/locust -r ~/Downloads/nkashy1-locust master HEAD --format yaml`
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/locust", line 33, in <module>
>     sys.exit(load_entry_point('bugout-locust==0.1.0', 'console_scripts', 'locust')())
>   File "/usr/local/lib/python3.8/site-packages/bugout_locust-0.1.0-py3.8.egg/locust/cli.py", line 69, in main
>   File "/usr/local/lib/python3.8/site-packages/bugout_locust-0.1.0-py3.8.egg/locust/git.py", line 47, in get_repository
> locust.git.GitRepositoryNotFound: No git repository found at path:/home/user/Downloads/nkashy1-locust
> ```

Is there a .git in that directory?

**Comment by kompotkot** [comment]
> > Hm somethings goes wrong with command
> > ` docker run -v ~/Downloads/nkashy1-locust bugout/locust -r ~/Downloads/nkashy1-locust master HEAD --format yaml`
> > ```
> > Traceback (most recent call last):
> >   File "/usr/local/bin/locust", line 33, in <module>
> >     sys.exit(load_entry_point('bugout-locust==0.1.0', 'console_scripts', 'locust')())
> >   File "/usr/local/lib/python3.8/site-packages/bugout_locust-0.1.0-py3.8.egg/locust/cli.py", line 69, in main
> >   File "/usr/local/lib/python3.8/site-packages/bugout_locust-0.1.0-py3.8.egg/locust/git.py", line 47, in get_repository
> > locust.git.GitRepositoryNotFound: No git repository found at path:/home/user/Downloads/nkashy1-locust
> > ```
> 
> Is there a .git in that directory?

Yes, I git cloned your nkashy1-locust fork.

**Comment by nkashy1** [comment]
> > > Hm somethings goes wrong with command
> > > ` docker run -v ~/Downloads/nkashy1-locust bugout/locust -r ~/Downloads/nkashy1-locust master HEAD --format yaml`
> > > ```
> > > Traceback (most recent call last):
> > >   File "/usr/local/bin/locust", line 33, in <module>
> > >     sys.exit(load_entry_point('bugout-locust==0.1.0', 'console_scripts', 'locust')())
> > >   File "/usr/local/lib/python3.8/site-packages/bugout_locust-0.1.0-py3.8.egg/locust/cli.py", line 69, in main
> > >   File "/usr/local/lib/python3.8/site-packages/bugout_locust-0.1.0-py3.8.egg/locust/git.py", line 47, in get_repository
> > > locust.git.GitRepositoryNotFound: No git repository found at path:/home/user/Downloads/nkashy1-locust
> > > ```
> > 
> > 
> > Is there a .git in that directory?
> 
> Yes, I git cloned your nkashy1-locust fork.

@kompotkot : Can you try this:
```
docker run -v /home/<username>/Downloads/nkashy1-locust:/opt/nkashy1-locust bugout/locust -r /opt/nkashy1-locust master HEAD --format yaml
```

**Comment by kompotkot** [comment]
Yes, this command works (with `main` instead of `master`)

**Pull request merged**
